<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>ThrowingNewInstanceOfSameException.kt</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">code-coverage-report</a> &gt; <a href="index.source.html" class="el_package">io.gitlab.arturbosch.detekt.rules.exceptions</a> &gt; <span class="el_source">ThrowingNewInstanceOfSameException.kt</span></div><h1>ThrowingNewInstanceOfSameException.kt</h1><pre class="source lang-java linenums">package io.gitlab.arturbosch.detekt.rules.exceptions

import io.gitlab.arturbosch.detekt.api.ActiveByDefault
import io.gitlab.arturbosch.detekt.api.CodeSmell
import io.gitlab.arturbosch.detekt.api.Config
import io.gitlab.arturbosch.detekt.api.Entity
import io.gitlab.arturbosch.detekt.api.Rule
import org.jetbrains.kotlin.psi.KtCallExpression
import org.jetbrains.kotlin.psi.KtCatchClause
import org.jetbrains.kotlin.psi.KtThrowExpression
import org.jetbrains.kotlin.psi.KtValueArgument
import org.jetbrains.kotlin.psi.psiUtil.findDescendantOfType

/**
 * Exceptions should not be wrapped inside the same exception type and then rethrown. Prefer wrapping exceptions in more
 * meaningful exception types.
 *
 * &lt;noncompliant&gt;
 * fun foo() {
 *     try {
 *         // ...
 *     } catch (e: IllegalStateException) {
 *         throw IllegalStateException(e) // rethrows the same exception
 *     }
 * }
 * &lt;/noncompliant&gt;
 *
 * &lt;compliant&gt;
 * fun foo() {
 *     try {
 *         // ...
 *     } catch (e: IllegalStateException) {
 *         throw MyException(e)
 *     }
 * }
 * &lt;/compliant&gt;
 */
@ActiveByDefault(since = &quot;1.16.0&quot;)
<span class="fc" id="L39">class ThrowingNewInstanceOfSameException(config: Config) : Rule(</span>
<span class="fc" id="L40">    config,</span>
<span class="fc" id="L41">    &quot;Avoid catch blocks that rethrow a caught exception wrapped inside a new instance of the same exception.&quot;</span>
) {

    override fun visitCatchSection(catchClause: KtCatchClause) {
<span class="pc bpc" id="L45" title="1 of 2 branches missed.">        val parameterName = catchClause.catchParameter?.name</span>
<span class="pc bpc" id="L46" title="2 of 4 branches missed.">        val typeReference = catchClause.catchParameter?.typeReference?.text</span>
<span class="pc bpc" id="L47" title="1 of 2 branches missed.">        val throwExpression = catchClause.catchBody?.findDescendantOfType&lt;KtThrowExpression&gt; {</span>
<span class="pc bpc" id="L48" title="1 of 2 branches missed.">            val thrownExpression = it.thrownExpression as? KtCallExpression</span>
<span class="pc bpc" id="L49" title="1 of 2 branches missed.">            thrownExpression != null &amp;&amp;</span>
<span class="fc bfc" id="L50" title="All 2 branches covered.">                createsSameExceptionType(thrownExpression, typeReference) &amp;&amp;</span>
<span class="fc bfc" id="L51" title="All 2 branches covered.">                hasSameExceptionParameter(thrownExpression.valueArguments, parameterName)</span>
        }
<span class="fc bfc" id="L53" title="All 2 branches covered.">        if (throwExpression != null) {</span>
<span class="fc" id="L54">            report(CodeSmell(Entity.from(throwExpression), description))</span>
        }
<span class="fc" id="L56">    }</span>

    private fun createsSameExceptionType(thrownExpression: KtCallExpression, typeReference: String?): Boolean =
<span class="pc bpc" id="L59" title="1 of 2 branches missed.">        thrownExpression.calleeExpression?.text == typeReference</span>

    private fun hasSameExceptionParameter(valueArguments: List&lt;KtValueArgument&gt;, parameterName: String?): Boolean =
<span class="pc bpc" id="L62" title="1 of 4 branches missed.">        valueArguments.size == 1 &amp;&amp; valueArguments.first().text == parameterName</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.13.202408290909</span></div></body></html>